feat: favorite_list.get_favorite_collected
Nemo2011/bilibili-api pull request #275
Opened 2023-05-03 07:50 UTC by HeavenElegy

# 添加`获取收藏合集`接口
- 1. 无

2023-05-04 14:14 UTC, z0z0r4 requested changes
可以考虑下添加 `ps` 每页项数参数？
以及按照其他函数通常 `pn` 为页码？

2023-05-04 14:19 UTC, Drelf2018 approved these changes

2023-05-04 16:24 UTC, HeavenElegy commented
> 

改了

2023-05-05 03:37 UTC, Drelf2018 approved these changes

2023-05-05 10:32 UTC, merged

2023-05-05 14:12 UTC, z0z0r4 commented
~~test两次可还行~~

2023-05-06 02:24 UTC, HeavenElegy commented
业务代码写多了,不写难受(*´д`)