Fix  #595
Nemo2011/bilibili-api pull request #680
Opened 2024-02-13 12:11 UTC by Nickszy

# {请说明更改}
- 1. {新增}
- 2. #595 -352风控问题，增加一个参数
- 3. {其他}

2024-02-14 05:00 UTC, z0z0r4 requested changes
为什么要用随机字符串代替现成的 const？

2024-02-15 08:13 UTC, Nickszy commented
emm 之前固定的参数也能用，随机的也行

2024-02-26 13:37 UTC, Nemo2011 commented
保险点最好别用随机字符串，写死较好，毕竟是通过字符串加密 base64 出来的，万一反爬虫策略严格一点随机字符串可能就有问题了。

~~虽然到那时候 `dm_img_iter` 可能也会查了，甚至这些参数的生成方式也会改。~~

2024-02-27 05:28 UTC, lb-chc commented
> 保险点最好别用随机字符串，写死较好，毕竟是通过字符串加密 base64 出来的，万一反爬虫策略严格一点随机字符串可能就有问题了。
> 
> ~虽然到那时候 `dm_img_iter` 可能也会查了，甚至这些参数的生成方式也会改。~

现有固定值会遭遇-352，join(random.sample(dm_rand, 2))是可运行的。要不你那边也测一下仅添加`'dm_img_inter' : '{"ds":[],"wh":[0,0,0],"of":[0,0,0]}'`后能不能运行？这个提交可能是完全可行的

以后再本地生成字符串并本地编码出来也行，固定值也很容易定点封掉吧

2024-04-05 06:19 UTC, merged